language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g yarn
  - cd src/client
  - yarn install
  - yarn build
after_success:
  - ./deploy.sh
sudo: false
env:
  global:
    - secure: U1JOM8GEYkC0RK4xmF3RYy7m+UVki9zJiEcQZCO9GNHavlkIL6k7Z4dfqRP7a1sZPhYqKU34AZuqSwTHukALAsM1QdIDDGx853fPZgdxBRIRPDuhT5hqfV1MvObw8rwjhFVnQoBvaaJ6kBdn/r68I8uwuNQEYXgM+lIuIP9rBogJEAoo38P3bLPOd4xIsdeZGXMUZfmwWC2SV/M7XIcG5hQDL7z7N45yZGYh8+KvKwkx8mWVN2dMCJ/p2D3+mApjIN+FkHZyqQkE29e8CKcA8kRvCtc82h/dCVlhkJXWEXsfrMtmRIo5XLQGYTVaSmi8+1yRG+88FrJl0/+jW9VlVZAaptsRX4BjbMBpAajkIjl21/iJU43GHeXlRXIKC4p/Kd6tmexF9vhrqMyBOCmQfDVKE8PkRhNV748dAl8Rlq+9cxKXAmTxafH2kijr8z9c7WQ4AMOUQPp/Pi9lXwohGoW0sjCGBvBHsjhkbT/WakTyxra2GjEtav8LXzxvCGf8qbXBhBPKDMjJEv0aW5vj8YTIcdL+lY1nUG22FTx1seLrTzQ/cVo0T/+0YSIkPUnflPTVcIubdDpNJEYQURzphfc/wiAZ3+LBRk61+76He14dtmrfk+pe562YqvQt3+peQbG+EPNzinKSil5Xy/5IonKS9VLPiHepcTsBA1Nbe/U=
    - secure: WAymCobzGfuVSD9wPevl13uaR2SGH/ZEqEjmvotojcIF5EoKdveXFWyz0n29LGE+GGi/HC4qhn7r8QsC/HoLp8HUFrro7EDBPKElVdgvB5DAzcIk0HIEWCODc1h3Vgw4C7jzY+fH5MKRdTqlPrnVkSVia+aV8434zn2tH4bTMob+ubY3y2d7fh8qwUDb8nUCBwyJUqscALbU0zhMWrrt7IA/WYKUVWHTSZwO1GRxzODVd/0cyfFyEFOLvpTomIaXFjSMgb4VffWK8Kx0WuDbH/M58cGa6gPpNQuTkexJobSrZHBkHDaDJ0hZSZhk2T6q1OeSMR6F4Rl2dZPh75/eqxUjJgOYcrU0pn/iftalwdDNj9VfJtinsKRl03hTQ17nEYGgmZ0Aq3ufkTNkvhsb85c6SZtDU4VUSx3+C5eaI72eVQFpjt8aFWwpw6QuQ2sc+42fg/5lDlKgf47DHeQ+c2bIYZGXVO9iSVxWDuezfr8T/CzAXBrkfoHG7PlhZuJC6euCF/Ao6vDOgIPaQjU1bsL0H0/COPRGDUDHUZJIxZukzHm1S9lonYIDJNQpavg7TxLKSrjcr7Qu/dMgMdflavhbirZhcqKshpUqhFSGkYqzZpfw3e22a3VGvoKlc+TiU80mYMhQqEgDPLKPm3/JvhNWvvVCz2NWo/w1t+gUKKU=
